### PR TITLE
Added an option to paper.yml to disable player data saving.

### PR DESCRIPTION
**Pull request by HyperPlay**
I've tested it. Works 100%. Only produces an exception (catched with a message) if a plugin manually tries to save player data using WorldNBTStorage methods.

### CODE REVIEW

**Comment by Techcable** [comment]
Why would you do this?

**Comment by HyperPlay** [comment]
Many minigame servers and hub/lobby servers don't need player data to be saved. By not accessing the file system everytime a player joins, load can be reduced and disk space can be saved.

**Comment by Byteflux** [comment]
Last I checked player data I/O was never a bottleneck. Do you have sampling or profiling data to prove player data loading/saving has a noticeable impact on server performance? I don't see any benefit to pulling this in otherwise.

You could either mount your playerdata folder as a ramdisk or just ignore the fact that it reads/writes player files since it's not a bottleneck. 

The reason I'm hesitant to add just any patch is because we have to maintain them forever. It's not practical for us to add any patch so we stick to only adding the ones we know make a real difference.

**Comment by HyperPlay** [comment]
Okay, no problem! I suppose it is not useful for most people.

**Pull request closed without merging**
